// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	vector<Person> person;
	int length;

	length = makePerson(person);
	REQUIRE(length == 100);
	printPerson(person);
	cout << "--------------------------------------------------\n";
}

TEST_CASE("Ex2 ", "[example]")
{
	vector<Person> person;
	int length;

	length = makePerson(person);
	sortPerson(person);
	printPerson(person);
	REQUIRE(person[0].no == 33);
	REQUIRE(person[99].no == 70);
	REQUIRE(person[50].no == 25);
	REQUIRE(person[75].no == 54);
	cout << "--------------------------------------------------\n";
}
